### ISSUE TITLE
Compatibility for beta8

### ISSUE THREAD

**Issue by PartialDevAdmin** [clarkwinkelmann/flarum-ext-emojionearea#10]
Will this extension be compatible with beta8?

**Comment by clarkwinkelmann** [comment]
I can't make any promise as the list of beta8 changes is not yet final but I will definitely try to update it for beta8.

I don't think the current latest version will work for beta8 due to the changes that affect nearly all extensions.

I'm closing this for now. Feel free to report any issue with beta8 once beta8 is out and that I've released a compatible version of this extension :wink:
