### ISSUE TITLE
Not flarum-style title

### ISSUE THREAD

**Issue by xtreh** [clarkwinkelmann/flarum-ext-emojionearea#19]
Not flarum style button emoji picker
[
![image](https://user-images.githubusercontent.com/28855581/82126423-e7719e80-97d6-11ea-9532-db17c1947cac.png)
](url)

[
![image](https://user-images.githubusercontent.com/28855581/82126456-2c95d080-97d7-11ea-8f0a-d3899ccddbba.png)
](url)

**Comment by clarkwinkelmann** [comment]
I'm aware of this, but it's not an easy fix.

Because the emoji button can't extend the `MarkdownButton` used by the markdown toolbar, it can't inherit the tooltip behavior.

Technically, it could be added by writing the additional code to initiate a tooltip. But the extra work isn't worth it. (Unless someone is ready to pay for this change of course...)

Other extension have also elected to not try to replicate the tooltip, like the Upload extension which simply doesn't have any title for its button.

I'm closing this as "won't fix".
